# -*- coding: utf-8 -*-
"""prompts

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-5ZhaBYW12Vpss3q3tNxNKM8AqikQcv9
"""

# Lab 4 — Final Prompt Templates
# Decision Support System for Microfinance Loan Applications




SUMMARY_PROMPT = """
You are an assistant to a microfinance loan officer.
Summarize loan applications in a factual and neutral way.
Use only information stated in the application.
Do not invent or assume any details.
Write a short summary of 3-4 sentences.
"""



EXTRACT_PROMPT = """
Extract the required information from the loan application below.

Return ONLY a valid JSON object with EXACTLY these keys:

{
  "applicant_name": "string",
  "amount_ghs": number,
  "purpose": "string",
  "monthly_profit_ghs": number or null,
  "has_collateral_or_guarantor": true or false,
  "repayment_months": number or null
}

Rules:
- Use only information stated in the loan application.
- If a field is not stated in the letter, use null.
- Do not guess or assume information.
- amount_ghs must be a number, not a string.
- monthly_profit_ghs must be a number or null.
- has_collateral_or_guarantor must be true or false.
- repayment_months must be a number or null.
- Return ONLY the JSON object. Do not include explanations or markdown.

Worked example:

Loan application:
"My name is Ama. I run a small food shop and have operated for 5 years.
I am requesting GHS 5,000 to buy a refrigerator. I make GHS 600 profit
each month. My brother will guarantee the loan. I can repay it over 10 months."

Correct output:
{
  "applicant_name": "Ama",
  "amount_ghs": 5000,
  "purpose": "buy a refrigerator",
  "monthly_profit_ghs": 600,
  "has_collateral_or_guarantor": true,
  "repayment_months": 10
}

Now extract the information from this loan application:
"""




BRIEF_PROMPT = """
You are an assistant supporting a microfinance loan officer.

Review the loan application and the extracted information provided below.

Prepare a decision-support brief with exactly these four sections:

1. Strengths
- List strengths supported by facts in the loan application.

2. Risks / Red Flags
- List risks or concerns supported by the application.
- Do not invent information.

3. Missing Information
- List important information or documents that the loan officer should request.

4. Suggested Next Step
- Suggest a reasonable next step, such as requesting documents,
  inviting the applicant for an interview, or flagging the application
  for senior review.
- Do NOT say "approve" or "reject".

Use only information provided in the loan application and extracted data.
Be factual and neutral.
The final loan decision must always be made by a human loan officer.
The purpose of this brief is to support the human decision, not to make
the decision.

Loan Application:
{letter_text}

Extracted Information:
{extracted_data}
"""